/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package cc.peitify.gradle

import spock.lang.Specification

class PeitifyPluginTest extends Specification {
//    def "someLibraryMethod returns true"() {
//        setup:
//        def lib = new PeitifyPlugin()
//
//        when:
//        def result = lib.someLibraryMethod()
//
//        then:
//        result == true
//    }
}
